# Generated by Django 5.1.3 on 2024-12-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightclass',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.federation'),
        ),
        migrations.AlterUniqueTogether(
            name='weightclass',
            unique_together={('name', 'gender', 'federation')},
        ),
    ]
