# Generated by Django 5.1.3 on 2024-12-20 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='address',
            field=models.CharField(blank=True, help_text="Athlete's address", max_length=255),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='coach',
            field=models.CharField(blank=True, help_text="Name of the athlete's coach", max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Athlete's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Athlete's height (in cm or inches)", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='home_gym',
            field=models.CharField(blank=True, help_text="Name of the athlete's primary gym", max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text="Athlete's preferred name or alias", max_length=50),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Athlete's phone number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='team_name',
            field=models.CharField(blank=True, help_text="Name of the athlete's team (if any)", max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Athlete's weight (in kg or lbs)", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Athlete's WhatsApp number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
