# Generated by Django 5.1.7 on 2025-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
