# Generated by Django 5.1.7 on 2025-06-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='first_time_setup',
            field=models.BooleanField(default=True, help_text='Whether to show the onboarding tour on first visit.'),
        ),
    ]
