# Generated by Django 5.1.3 on 2024-12-29 22:22

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightclass',
            options={'ordering': [django.db.models.functions.comparison.Cast('name', output_field=models.IntegerField())]},
        ),
    ]
