# Generated by Django 5.1.3 on 2024-12-20 15:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_athleteprofile_address_athleteprofile_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Athlete's phone number", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Athlete's WhatsApp number", max_length=128, region=None),
        ),
    ]
