# Generated by Django 5.1.3 on 2024-12-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_weightclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightclass',
            name='weight_d',
            field=models.CharField(choices=[('u', 'u'), ('+', '+')], default='u', max_length=2),
            preserve_default=False,
        ),
    ]
