# Generated by Django 5.1.7 on 2025-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizerprofile_first_time_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/athlete_default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
