# Generated by Django 5.1.7 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_athleteprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
