# Generated by Django 5.1.3 on 2025-01-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_weightclass_weight_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='x_name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
