# Generated by Django 5.1.7 on 2025-06-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_athleteprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='slug',
        ),
    ]
