# Generated by Django 5.1.3 on 2025-01-03 15:59

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_facebook_name_alter_user_instagram_name_and_more'),
        ('competitions', '0006_alter_divisionweightclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightclass',
            options={'ordering': [django.db.models.functions.comparison.Cast('name', output_field=models.DecimalField())]},
        ),
        migrations.AlterUniqueTogether(
            name='weightclass',
            unique_together={('gender', 'federation')},
        ),
        migrations.AlterField(
            model_name='weightclass',
            name='name',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
