# Generated by Django 5.1.7 on 2025-07-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_terms_accepted_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strongman_status',
            field=models.CharField(choices=[('Amateur', 'Amateur'), ('Pro', 'Pro')], default='Amateur', max_length=10),
        ),
    ]
