# Generated by Django 5.1.3 on 2025-01-03 16:10

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_weightclass_options_alter_weightclass_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightclass',
            options={'ordering': [models.Case(models.When(name__regex='^\\d+(\\.\\d+)?$', then=django.db.models.functions.comparison.Cast('name', output_field=models.DecimalField(decimal_places=2, max_digits=5))), default=models.Value(0, output_field=models.DecimalField(decimal_places=2, max_digits=5)))]},
        ),
    ]
