# Generated by Django 5.1.3 on 2025-01-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_weightclass_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightclass',
            unique_together=set(),
        ),
    ]
