# Generated by Django 5.1.3 on 2025-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_division_competition_division_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Provide a custom division name if none of the predefined names apply.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(blank=True, choices=[('novice', 'Novice'), ('teen', 'Teen'), ('master', 'Master'), ('open', 'Open'), ('adaptive', 'Adaptive'), ('pro', 'Pro')], help_text='Choose a predefined name or leave blank to set a custom name.', max_length=50, null=True),
        ),
    ]
