# Generated by Django 5.1.3 on 2025-01-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_division_custom_name_alter_division_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='name',
            new_name='predefined_name',
        ),
    ]
