# Generated by Django 5.1.3 on 2025-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_name_division_predefined_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightclass',
            name='name',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight'),
        ),
    ]
