# Generated by Django 5.1.3 on 2025-02-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_weightclass_division'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightclass',
            unique_together={('name', 'gender', 'division')},
        ),
        migrations.AlterField(
            model_name='weightclass',
            name='federation',
            field=models.ForeignKey(help_text='Federation that defines this weight class.', on_delete=django.db.models.deletion.CASCADE, related_name='weight_classes', to='competitions.federation'),
        ),
        migrations.RemoveField(
            model_name='weightclass',
            name='competition',
        ),
    ]
