# Generated by Django 5.1.3 on 2025-03-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_weightclass_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteEventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(blank=True, help_text="Type of note (e.g., 'yoke_height', 'opening_weight')", max_length=100)),
                ('note_value', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to='competitions.athletecompetition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.event')),
            ],
            options={
                'ordering': ['event__order', 'note_type'],
                'unique_together': {('athlete_competition', 'event', 'note_type')},
            },
        ),
    ]
