# Generated by Django 5.1.3 on 2025-03-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_athleteeventnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_lanes',
            field=models.PositiveIntegerField(default=1, help_text='Number of lanes for this event. Set to 1 for single-lane events.'),
        ),
        migrations.CreateModel(
            name='LaneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.PositiveIntegerField(help_text='Lane number assigned to this athlete for this event.')),
                ('heat_number', models.PositiveIntegerField(default=1, help_text='Heat number for events with multiple heats.')),
                ('athlete_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_assignments', to='competitions.athletecompetition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_assignments', to='competitions.event')),
            ],
            options={
                'ordering': ['event', 'heat_number', 'lane_number'],
                'unique_together': {('athlete_competition', 'event')},
            },
        ),
    ]
