# Generated by Django 5.1.3 on 2025-03-14 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_event_number_of_lanes_laneassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRunOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('lane_number', models.PositiveIntegerField(blank=True, null=True)),
                ('heat_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('athlete_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_orders', to='competitions.athletecompetition')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_orders', to='competitions.competition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_orders', to='competitions.event')),
            ],
            options={
                'ordering': ['event', 'order'],
                'unique_together': {('competition', 'event', 'athlete_competition'), ('competition', 'event', 'order')},
            },
        ),
    ]
