# Generated by Django 5.1.3 on 2025-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_weightclass_options'),
        ('competitions', '0006_alter_divisionweightclass_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='divisionweightclass',
            unique_together={('division', 'weight_class')},
        ),
    ]
