# Generated by Django 5.1.3 on 2025-01-03 16:42

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_divisionweightclass_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionweightclass',
            options={'ordering': ['division__name', django.db.models.functions.comparison.Cast(django.db.models.functions.comparison.Coalesce('weight_class__name', models.Value(0)), output_field=models.DecimalField())]},
        ),
    ]
