# Generated by Django 5.1.7 on 2025-05-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_result_points_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionEventImplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement_name', models.CharField(help_text='E.g. Log, Yoke, Farmer’s', max_length=100)),
                ('base_weight', models.DecimalField(decimal_places=2, help_text='Base implement weight (no plates)', max_digits=6)),
                ('weight_unit', models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=20)),
                ('load_points', models.PositiveSmallIntegerField(choices=[(1, 'Single-sided'), (2, 'Two-sided'), (4, 'Four-sided')], default=2, help_text='How many sides you’ll load plates on')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_event_implements', to='competitions.division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_implements', to='competitions.event')),
            ],
            options={
                'unique_together': {('event', 'division', 'implement_name')},
            },
        ),
    ]
