# Generated by Django 5.1.3 on 2025-01-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_divisionweightclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionweightclass',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='divisionweightclass',
            unique_together=set(),
        ),
    ]
