# Generated by Django 5.1.3 on 2025-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_divisionweightclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divisionweightclass',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
