# Generated by Django 5.1.3 on 2025-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_sponsor_display_order_sponsor_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL for the competition', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL for the competition', null=True),
        ),
    ]
