# Generated by Django 5.1.7 on 2025-06-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_implementdefinition_delete_eventimplementdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimplement',
            name='implement_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_uses', to='competitions.implementdefinition'),
        ),
    ]
