# Generated by Django 5.1.3 on 2025-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_tshirtsize_competition_provides_shirts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allowed_tshirt_sizes',
            field=models.ManyToManyField(blank=True, help_text='Select the T-shirt sizes that athletes can choose from.', to='competitions.tshirtsize'),
        ),
    ]
