# Generated by Django 5.1.3 on 2025-01-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_competition_allowed_tshirt_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletecompetition',
            name='weigh_in',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Athlete's weight (lbs) recorded at the competition weigh-in.", max_digits=5, null=True),
        ),
    ]
