# Generated by Django 5.1.3 on 2025-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_athletecompetition_weigh_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('waiting', 'Waiting')], default='waiting', help_text='Indicates if the competition is approved by the admin.', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='publication_status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', help_text='Indicates if the competition is published by the organizer.', max_length=12),
        ),
    ]
