# Generated by Django 5.1.7 on 2025-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_athleteeventnote_note_value_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteeventnote',
            name='attempt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
