# Generated by Django 5.1.7 on 2025-06-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_athleteeventnote_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tags',
            field=models.ManyToManyField(blank=True, to='competitions.tag'),
        ),
    ]
