# Generated by Django 5.1.3 on 2025-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_competition_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Send an email to the organizer every time an athlete signs up.'),
        ),
    ]
