# Generated by Django 5.1.7 on 2025-06-15 23:54

import django.db.models.deletion
from django.db import migrations, models

def backfill_weightclass_competition(apps, schema_editor):
    WeightClass = apps.get_model("competitions", "WeightClass")
    for wc in WeightClass.objects.all():
        if wc.division and wc.division.competition_id:
            wc.competition_id = wc.division.competition_id
            wc.save(update_fields=["competition"])


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_competition_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name="weightclass",
            name="competition",
            field=models.ForeignKey(
                to="competitions.competition",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_classes",
                null=True,
                blank=True,
                help_text="Competition this weight class belongs to.",
            ),
        ),
        migrations.RunPython(backfill_weightclass_competition),
        migrations.AlterField(
            model_name="weightclass",
            name="competition",
            field=models.ForeignKey(
                to="competitions.competition",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_classes",
                help_text="Competition this weight class belongs to.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weightclass",
            unique_together={("name", "gender", "division", "competition")},
        ),
    ]


