# Generated by Django 5.1.3 on 2025-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_competition_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_multiple_implements',
            field=models.BooleanField(default=False, help_text='Check if the event has multiple implements.'),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_implements',
            field=models.PositiveIntegerField(blank=True, help_text='Number of implements if the event has multiple implements.', null=True),
        ),
    ]
