# Generated by Django 5.1.3 on 2025-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_event_has_multiple_implements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
