# Generated by Django 5.1.7 on 2025-06-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_alter_weightclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsize',
            name='style',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('mens', "Men's"), ('womens', "Women's"), ('youth', 'Youth')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='weightclass',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='Competition this weight class belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_classes', to='competitions.competition'),
        ),
        migrations.AlterUniqueTogether(
            name='tshirtsize',
            unique_together={('style', 'size')},
        ),
    ]
