# Generated by Django 5.1.7 on 2025-06-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_competition_current_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionrunorder',
            unique_together=set(),
        ),
    ]
