# Generated by Django 5.1.7 on 2025-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_competitionstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimplement',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight of the implement.', null=True),
        ),
    ]
