# Generated by Django 5.1.7 on 2025-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_alter_eventimplement_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='auto_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
