# Generated by Django 5.1.7 on 2025-07-24 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_competition_auto_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalsQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_type', models.CharField(choices=[('Local', 'Local'), ('Regional', 'Regional'), ('Pro/Am', 'Pro/Am')], max_length=20)),
                ('competition_date', models.DateField()),
                ('division', models.CharField(max_length=100)),
                ('weight_class', models.CharField(max_length=100)),
                ('placing', models.PositiveIntegerField()),
                ('qualification_reason', models.TextField()),
                ('qualified_on', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'verbose_name': 'Nationals Qualifier',
                'verbose_name_plural': 'Nationals Qualifiers',
            },
        ),
    ]
