# Generated by Django 5.1.7 on 2025-07-24 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_nationalsqualifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nationalsqualifier',
            unique_together={('athlete', 'competition', 'division', 'weight_class')},
        ),
    ]
