# Generated by Django 5.1.7 on 2025-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_alter_nationalsqualifier_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When this competition should automatically become published.', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_open_at',
            field=models.DateTimeField(blank=True, help_text='When registration becomes available. Countdown will be shown until this time.', null=True),
        ),
    ]
