# Generated by Django 5.1.7 on 2025-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_competition_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
