# Generated by Django 5.1.7 on 2025-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_federation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federation',
            name='slug',
        ),
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
